/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DogCard: typeof import('./src/components/DogCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LocationMap: typeof import('./src/components/LocationMap.vue')['default']
    MarqueeCard: typeof import('./src/components/MarqueeCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteHeader: typeof import('./src/components/SiteHeader.vue')['default']
  }
}
